'use client';
import type { Metadata } from "next";

import Image from 'next/image';
import ArrowRight from '@/app/arrow-right.svg';
import Trash from '@/app/trash.svg';
import Edit from '@/app/edit.svg';
import Download from '@/app/download.svg';
import Copy from '@/app/copy.svg';
import Options from '@/app/three-dots.svg';

import CopyText from "@/app/assistant/CopyText";
import { useState } from "react";

// export const metadata: Metadata = {
//     title: "Qurela - AI Асистент",
//     description: "Generated by create next app",
//   };

export default function Home() {
  const [edit, setEdit] = useState(false);
  const editFunc = () => {
    console.log('works')
    setEdit(true);
  }

    return (
      <main className="flex items-center pt-12 min-h-[100vh] items-center">
        {edit && (
          <div className="fixed w-full h-full z-[10000] top-0 flex justify-center items-center">
            <span className="bg-green-500 w-[400px] h-[200px]">

            </span>
          </div>
        )}
        <div className="flex w-[80%] h-[80vh] m-auto gap-7 items-stretched">
          <div className="flex-[3] flex gap-6 flex-col justify-stretched">
            <form className="flex flex-col h-10 rounded-xl flex-[4] bg-white">
              <textarea placeholder="Съобщение до Qurela" autoFocus className="flex-[8] m-4 outline-none"></textarea>
              <div className="flex-[2] flex justify-between m-2">
                <select
                  className="bg-platinum-gray rounded-full flex justify-center items-center cursor-pointer text-center text-sm outline-none "
                >
                  <option data-type="check" value="Проверка на информация">Проверка</option>
                  <option data-type="question" value="Задайте въпрос">Въпрос</option>
                  <option data-type="summarize" value="Обобщи информация">Обобщение</option>
                </select>
                <button
                  className="aspect-square bg-marian-blue rounded-full flex justify-center items-center cursor-pointer"
                  title="Изпращане"
                >
                  <Image src={ArrowRight} alt=" " />
                </button>
              </div>
            </form>

            <div className="relative bg-white rounded-xl flex-[5] overflow-hidden flex flex-col">
              <h3 className="flex-[3] border-l-green-500 border-l-[7px] flex items-center">
                <span className="mx-2 text-base font-semibold">
                  Всички ще умрем
                </span>
              </h3>
              <button 
              onClick={CopyText}
              className="absolute top-2 right-2 rounded-xl transition-all active:bg-gray-300 flex items-center justify-center w-8 h-8" title="Копиране">
                <Image src={Copy} alt=""></Image>
              </button>
              <p className="flex-[9] h-max border-l-gray-300 border-l-[7px] flex">
  <span
    className="mx-2 my-5 text-sm overflow-y-auto h-[150px] copy-text">
    hi
  </span>
</p>

              <div className="flex-[2] w-full h-[10%] bg-gray-300 flex gap-4 px-4 justify-end">
                <div className="flex items-center cursor-pointer">
                  <Image src={Download} alt=''></Image>
                  <span>Изтегляне</span>
                </div>

                <button 
                onClick={editFunc}
                className="flex items-center cursor-pointer">
                  <Image src={Edit} alt=''></Image>
                  <span>Редактиране</span>
                </button>

                <div className="flex items-center cursor-pointer">
                  <Image src={Trash} alt=''></Image>
                  <span>Изтриване</span>
                </div>
              </div>
            </div>
          </div>

          <div className="flex-[2] bg-platinum-gray rounded-2xl overflow-hidden"> 
            <h3 className="w-[100%] bg-jordy-blue px-3 py-2 font-semibold text-base">Последни чатове</h3>
            <ul className="text-sm m-0 flex flex-col cursor-pointer">
            <li className="p-2 border-b-gray-300 border-b-[2px] hover:bg-gray-300 m-0 relative basis-[55px] flex items-center">
              <span>Какви са симптомите на диабет тип 2 и как се диагностицира?</span>
              <span className="h-full w-[20%] bg-gradient-to-r from-transparent via-platinum-gray to-platinum-gray hover:from-transparent hover:via-gray-300 hover:to-gray-300 absolute top-0 right-0"></span>
              <span className="h-full aspect-square absolute top-0 right-0 flex justify-center items-center">
                <Image src={Options} alt=""></Image>
              </span>
            </li>

              
              <li className="p-2 border-b-gray-300 border-b-[2px] hover:bg-gray-300 m-0 relative basis-[55px] flex items-center">
                <span className="">Каква е разликата между вирусна и бактериална инфекция?</span>
                <span className="h-full w-[20%] bg-gradient-to-r from-transparent via-platinum-gray to-platinum-gray hover:from-transparent hover:via-gray-300 hover:to-gray-300 absolute top-0 right-0"></span>
                <span className="h-full aspect-square absolute top-0 right-0 flex justify-center items-center">
                  <Image src={Options} alt=""></Image>
                </span>
              </li>
              
              <li className="p-2 border-b-gray-300 border-b-[2px] hover:bg-gray-300 m-0 relative basis-[55px] flex items-center">
                <span className="">Какви са основните рискови фактори за сърдечно-съдови заболявания?</span>
                <span className="h-full w-[20%] bg-gradient-to-r from-transparent via-platinum-gray to-platinum-gray hover:from-transparent hover:via-gray-300 hover:to-gray-300 absolute top-0 right-0"></span>
                <span className="h-full aspect-square absolute top-0 right-0 flex justify-center items-center">
                  <Image src={Options} alt=""></Image>
                </span>
              </li>
              
              <li className="p-2 border-b-gray-300 border-b-[2px] hover:bg-gray-300 m-0 relative basis-[55px] flex items-center">
                <span className="">Какво е значение на имунната система и какво може да я отслаби?</span>
                <span className="h-full w-[20%] bg-gradient-to-r from-transparent via-platinum-gray to-platinum-gray hover:from-transparent hover:via-gray-300 hover:to-gray-300 absolute top-0 right-0"></span>
                <span className="h-full aspect-square absolute top-0 right-0 flex justify-center items-center">
                  <Image src={Options} alt=""></Image>
                </span>
              </li>
            </ul>
          </div>
        </div>
      </main>
    );
  }
  